---
title: "Lung cancer: Late Stages"
author: '[F. Javier Rubio](https://sites.google.com/site/fjavierrubio67/), Danilo Alvares, Daniel Redondo-Sanchez and Miguel Angel Luque-Fernandez'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    toc_float: true
---

# Data Preparation


```{r message=FALSE}
rm(list=ls())
# Required packages
library(survival)
library(devtools)
#install_github("davidrusi/mombf")
library(mombf)
library(lubridate)
library(forcats)
library(glmnet)
library(ggplot2)
library(dplyr)

# Reading the data
#setwd("/Users/FJRubio/Dropbox/Survival_Comorb/MasterData")
survdata <- read.csv("LUNG.csv", header = TRUE, stringsAsFactors=FALSE)
head(survdata)
dim(survdata)
colnames(survdata)

##################################################################
# COMPLETE DATA CASES: response variable and design matrix
##################################################################

# Complete cases (indicate which variables we will include in the analysis only)
# hemiplegia removed as there are only 2 cases
dput(colnames(survdata))
# index of variables of interest
ind.v <- c("status", "datainci", "datefoll", 
           "age", "gender", "infarct", "LocAdv", 
           "heart_failure", "vascular_disease", 
           "cerebro_disease", "dementia", "pulmonary_disease", "connective_disease", 
           "renal_disease", "diabetes", "liver_grouped","smoker")

survdatac <- survdata[,ind.v]
dim(survdatac)
colnames(survdatac)

rm(survdata)

# complete cases of variables of interest
ind.cc <- complete.cases(survdatac) 
mean(ind.cc) # completeness proportion

survdatac <- survdatac[ind.cc,]

# complete cases for TNM
survdatac$LocAdv <- factor(survdatac$LocAdv)
indTNM <- which(survdatac$LocAdv ==   levels(survdatac$LocAdv)[1]) 

survdatac <- survdatac[-indTNM,]

dim(survdatac)

# Late Stage
ind.late <- which(c(as.numeric(survdatac$LocAdv) - 2) == 1)

survdatac <- survdatac[ind.late,]

dim(survdatac)


# Survival times
survdatac$time <- as.numeric(time_length(interval(dmy(survdatac$datainci), dmy(survdatac$datefoll)), "year"))
hist(survdatac$time, breaks = 50, xlab = "time", probability = TRUE, main = "")
box()

# Vital status (0 - alive, 1 - dead)
survdatac$status <- as.numeric(survdatac$status - 1)
mean(survdatac$status)

# log Survival times and status
y <- Surv(log(survdatac$time), event=survdatac$status)

# index containing the variables of interest
indX <- (1:ncol(survdatac))[!colnames(survdatac)%in%c("status","datainci","datefoll","time","LocAdv")] 

# Design matrix
X <- survdatac[,indX] 

# Transforming comorbidities to 0s and 1s
for(i in 2:(ncol(X)-1) ) X[,i] <- ifelse(X[,i] == 2, 0,  1) 

# Standardising all dummy variables
X[,1:(ncol(X)-1)] <- apply(X[,1:(ncol(X)-1)],2,scale) 

# Smoking status as a categorical variable
table(X$smoker)
X$smoker <- factor(X$smoker, levels = c(3, 1, 2),
                   labels = c("Never smoked", "Current smoker", "Previous smoker"), ordered = T)
table(X$smoker)

head(X)
```

# Bayesian variable selection

```{r}
#####################################################################
# Bayesian Variable Selection
#####################################################################

# Priors
priorCoefz = zellnerprior(taustd=1) # g-prior
priorCoefm= momprior(taustd=1) # p-mom
priorGroup= groupzellnerprior(taustd=1)

## LINEAR EFFECTS ##
####################
f= formula(paste('y ~ ',paste('X[,',1:ncol(X),']',sep='',collapse="+"),sep=''))

mslinz <- modelSelection(f, priorCoef= priorCoefz, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)
mslinm <- modelSelection(f, priorCoef= priorCoefm, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)

new.names <- c("Intercept",head(colnames(X),n=-1), "smoker1", "smoker2")

#MARGINAL POSTERIOR INCLUSION PROB FOR Zellner's prior
margpp.aftz = mslinz$margpp
names(margpp.aftz) <- new.names
pp.aftz= postProb(mslinz)
margpp.aftz
head(pp.aftz)
#MARGINAL POSTERIOR INCLUSION PROB FOR AFT-pMOMZ 
margpp.aftmom = mslinm$margpp
names(margpp.aftmom) <- new.names
pp.aftmom= postProb(mslinm)
margpp.aftmom
head(pp.aftmom)

# Order variables by inclusion probability
new.names[order(margpp.aftmom, decreasing = TRUE)]

cbind(new.names[order(margpp.aftmom, decreasing = TRUE)],margpp.aftmom[order(margpp.aftmom, decreasing = TRUE)])

new.names[order(margpp.aftz, decreasing = TRUE)]


cbind(margpp.aftz,margpp.aftmom)

barplot(margpp.aftmom[order(margpp.aftmom, decreasing = FALSE)], main="Inclusion Probability", horiz=TRUE,
        names.arg = new.names[order(margpp.aftmom, decreasing = FALSE)],las=1, cex.names = 0.5)
box()
```

# Plots 

```{r, fig.width = 12, fig.height = 7}
margpp.aftmom <- margpp.aftmom[-which(names(margpp.aftmom) == "Intercept")]
data_plot <- order(margpp.aftmom, decreasing = FALSE)
data_plot_names <- names(margpp.aftmom)[order(margpp.aftmom, decreasing = FALSE)]

data_plot_names
data_plot_names <- c("Liver disease", "Diabetes", "Renal disease", "Pulmonary disease", 
                     "Connective disease", "Heart failure", "Infarct", "Vascular disease",
                     "Cerebrovascular disease", "Dementia", "Current smoker", "Previous smoker",  
                     "Gender", "Age") # Fix labels
data_plot_names

data.frame(y = margpp.aftmom[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))

ggsave("variable_importance.png", width = 12, height = 7, dpi = 300)
```

# Sensitivity analysis using Cox-LASSO

```{r}

#####################################################################
# Cox-LASSO (sensitivity analysis)
#####################################################################

# Survival object with times
y2 <- Surv(time = survdatac$time, event=survdatac$status)

X2 <- X[,1:(ncol(X)-1)]

smoking <- matrix(0, ncol = 3, nrow = nrow(X))
colnames(smoking) <- c("smoker 1", "smoker 2", "smoker 3")


for(i in 1:nrow(X)) smoking[i,X$smoker[i]] <- 1

X2 <- data.matrix(cbind(X2,smoking[,2:3]))
head(X2)

cv.fit= try(cv.glmnet(x =  X2, y = y2, family="cox", 
                      maxit=10000, nfolds=10, alpha=1), silent=TRUE)
fit= try(glmnet(x = X2, y=y2, family = "cox", maxit=10000, alpha=1), silent=TRUE)

# active variables (lambda.min)
b.coxlasso = as.double(coef(fit, s=cv.fit$lambda.min))
new.names[-1][which(b.coxlasso!=0)]

# active variables (lambda.1se)
b2.coxlasso = as.double(coef(fit, s=cv.fit$lambda.1se))
new.names[-1][which(b2.coxlasso!=0)]
```
