---
title: "MI - Colorectal cancer: Late Stage"
author: '[F. Javier Rubio](https://sites.google.com/site/fjavierrubio67/), Danilo Alvares, Daniel Redondo-Sanchez and Miguel Angel Luque-Fernandez'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: true
    toc_float: true
---

# Data Preparation

```{r message=FALSE}
rm(list=ls())
# Required packages
library(survival)
library(devtools)
#install_github("davidrusi/mombf")
library(mombf)
library(lubridate)
library(forcats)
library(glmnet)
library(ggplot2)
library(dplyr)

# Reading the data
survdata <- read.csv("CRCimputed.csv", header = TRUE, stringsAsFactors=FALSE)
head(survdata)
dim(survdata)
colnames(survdata)

##################################################################
# Response variable and design matrix
##################################################################

# Complete cases (indicate which variables we will include in the analysis only)
dput(colnames(survdata))
# index of variables of interest
ind.v <- c("status", "dci", "dof", "age", "sex", "infarct", 
           "heart_failure", "vascular_disease", "cerebro_disease", "dementia", 
           "pulmonary_disease", "connective_disease", "hemiplegia", "renal_disease", 
           "diabetes", "liver", "stage")

# Sample size
n <- dim(survdata)[1]/6

# Imputed data sets
survdataMI <- survdata[-c(1:n),ind.v]

colnames(survdataMI)

rm(survdata)
```

# Bayesian variable selection for imputed data sets

```{r}
# Initialising lists
margpp.aftz = pp.aftz= margpp.aftmom = pp.aftmom = list()


for(k in 1:5){

# Extracting late stage patients
ind.late <- which(survdataMI$stage[ ((k-1)*n+1):(k*n) ] == 4)

survdatak <- survdataMI[ ((k-1)*n+1):(k*n), ][ind.late,]

# Survival times
survdatak$time <- as.numeric(time_length(interval(dmy(survdatak$dci), dmy(survdatak$dof)), "year"))

# log Survival times and status
y <- Surv(log(survdatak$time), event=survdatak$status)

# index containing the variables of interest
indX <- (1:ncol(survdatak))[!colnames(survdatak)%in%c("status","dci","dof","time")] 

# Design matrix without stage
X <- as.matrix(survdatak[,head(indX,-1)] )


##################################################################################
# Transforming sex to 0s and 1s
##################################################################################
X[,"sex"] <- ifelse(X[,"sex"] == 2, 0,  1) 

# Standardising all dummy variables
X <- apply(X,2,scale) 

#####################################################################
# Bayesian Variable Selection
#####################################################################

# Priors
priorCoefz = zellnerprior(taustd=1) # g-prior
priorCoefm= momprior(taustd=1) # p-mom
priorGroup= groupzellnerprior(taustd=1)

## LINEAR EFFECTS ##
####################
f= formula(paste('y ~ ',paste('X[,',1:ncol(X),']',sep='',collapse="+"),sep=''))

mslinm <- modelSelection(f, priorCoef= priorCoefm, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)

#MARGINAL POSTERIOR INCLUSION PROB FOR AFT-pMOMZ 
margpp.aftmom[[k]] = mslinm$margpp
pp.aftmom[[k]] = postProb(mslinm)

}
```

# Posterior Summaries for BVS in imputed data sets

```{r}

#MARGINAL POSTERIOR INCLUSION PROB FOR AFT-pMOMZ 
new.names <- c("Intercept",colnames(X))
for(k in 1:5) names(margpp.aftmom[[k]]) <- new.names

for(k in 1:5){

writeLines("##################################################################")
writeLines(paste("Imputed data set k = ", k))
writeLines("##################################################################")

# Posterior Inclusion Probabilities
print(margpp.aftmom[[k]])

# Posterior Model Probabilities  
print(head(pp.aftmom[[k]]))

}

```

# Plots for BVS in imputed data sets

```{r}
marg.app <- margpp.aftmom

## --------------------------------------------------------------------------------------------------------------------------------------
for(k in 1:5){
  writeLines("##################################################################")
  writeLines(paste("Imputed data set k = ", k))
  writeLines("##################################################################")
  
  # Plot
  marg.app[[k]] <- marg.app[[k]][-which(names(marg.app[[k]]) == "Intercept")]
  data_plot <- order(marg.app[[k]], decreasing = FALSE)
  data_plot_names <- names(marg.app[[k]])[order(marg.app[[k]], decreasing = FALSE)]
  
  data_plot_names
data_plot_names <- c("Cerebrovascular disease", "Dementia", "Gender", "Pulmonary disease",
                     "Vascular disease","Connective disease", "Hemiplegia", "Heart failure",
                     "Liver disease", "Infarct", "Renal disease", "Diabetes",
                     "Age") # Fix labels
  data_plot_names
  
  print(  data.frame(y = marg.app[[k]][data_plot],
             x = factor(data_plot_names,
                        data_plot_names,
                        ordered = T)) %>% 
    ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
    geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
    geom_text(nudge_y = 0.02) + 
    xlab("") +
    scale_y_continuous(name = "Posterior inclusion probability",
                       expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
    coord_flip() +
    theme_classic() + 
    theme(axis.text = element_text(size = 10, color = "black"),
          axis.title.x = element_text(size = 13, vjust = 0.1))
)
}
```

# Average PIP over imputed data sets

```{r}
# Average PIP
pip <- matrix(0, ncol = 5, nrow = length(margpp.aftmom[[1]]))

for(k in 1:5) pip[,k] <- margpp.aftmom[[k]]

gr.pip <- apply(pip,1,mean)

names(gr.pip) <- names(margpp.aftmom[[1]])


# Plot
gr.pip <- gr.pip[-which(names(gr.pip) == "Intercept")]
data_plot <- order(gr.pip, decreasing = FALSE)
data_plot_names <- names(gr.pip)[order(gr.pip, decreasing = FALSE)]

data_plot_names
data_plot_names <- c("Cerebrovascular disease", "Dementia", "Gender", "Pulmonary disease",
                     "Vascular disease","Connective disease", "Hemiplegia", "Heart failure",
                     "Liver disease", "Infarct", "Renal disease", "Diabetes",
                     "Age") # Fix labels
data_plot_names

data.frame(y = gr.pip[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
```